#
# Copyright 2017, Data61
# Commonwealth Scientific and Industrial Research Organisation (CSIRO)
# ABN 41 687 119 230.
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(DATA61_BSD)
#

apps-$(CONFIG_APP_ROOTTASK)        += roottask

# list of libraries the app needs to build
roottask-y                          = common libsel4 libmuslc libsel4vka libcpio libelf \
                                      libsel4allocman  \
                                      libsel4platsupport libsel4platsupport libsel4muslcsys \
                                      libsel4simple libsel4vspace libsel4utils libutils libsel4debug \
                                      libsel4sync libsel4serialserver

# set up correct simple lib for our kernel
roottask-y += libsel4simple-default
roottask-components=$(addprefix $(STAGE_BASE)/bin/sel4/, $(roottask-components-y))

roottask: export COMPONENTS=${roottask-components}


roottask: kernel_elf $(roottask-y) $(roottask-components-y)
